# Development VM — Global variables.
#

$developer_email = "wfo@worldfloraonline.org"

# May be used in URLs generated by emails etc.
$container_hostname = "localhost"

# Set $proxy to "http://proxy:8080" (for example) to enable.
$proxy = ""
$no_proxy = ""

# Google Cloud mirror
$ubuntu_source = "gce.clouds.archive.ubuntu.com"
# Normal country-code mirror
#$ubuntu_source = "gb.archive.ubuntu.com"

$database_host = "10.240.0.14"
$portal_host = "10.240.0.13"
$harvester_host = "10.240.0.15"
$image_host = "10.240.0.19"
$database_host_external = "130.211.148.182"
$harvester_host_external = "35.188.64.88"
$image_host_external = "130.211.152.120"