# Development VM — Global variables.
#

$developer_email = "sunitha.katabathuni@gmail.com"

# May be used in URLs generated by emails etc.
$container_hostname = "localhost"

# Set $proxy to "http://proxy:8080" (for example) to enable.
$proxy = ""
$no_proxy = ""

# Google Cloud mirror
$ubuntu_source = "gce.clouds.archive.ubuntu.com"
# Normal country-code mirror
#$ubuntu_source = "gb.archive.ubuntu.com"

$database_host = "10.240.0.26"
$portal_host = "10.240.0.24"
$harvester_host = "10.240.0.27"
$image_host = "10.240.0.28"
$database_host_external = "35.192.115.4"
$harvester_host_external = "35.192.134.244"
$image_host_external = "104.154.199.170 "